# Generated by Django 4.2 on 2023-04-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_alter_objectpermission_object_ct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectpermission',
            options={'verbose_name': 'User Object Permission', 'verbose_name_plural': 'User Object Permissions'},
        ),
    ]
