# Generated by Django 4.2 on 2023-04-30 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safety', '0009_alter_objectgroup_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectgroupuser',
            options={'verbose_name': 'Object Group User', 'verbose_name_plural': 'Object Group Users'},
        ),
        migrations.AlterUniqueTogether(
            name='objectgroupuser',
            unique_together={('group', 'user')},
        ),
    ]
