# Generated by Django 4.2.5 on 2023-09-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('safety_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteuser',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
