# Generated by Django 4.2.5 on 2023-09-14 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('safety_tests', '0002_alter_remoteuser_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteUser',
        ),
    ]
